export const US_CITIES = [
  { name: 'Birmingham', stateCode: 'AL' },
  { name: 'Huntsville', stateCode: 'AL' },
  { name: 'Mobile', stateCode: 'AL' },
  { name: 'Anchorage', stateCode: 'AK' },
  { name: 'Fairbanks', stateCode: 'AK' },
  { name: 'Juneau', stateCode: 'AK' },
  { name: 'Phoenix', stateCode: 'AZ' },
  { name: 'Tucson', stateCode: 'AZ' },
  { name: 'Mesa', stateCode: 'AZ' },
  { name: 'Little Rock', stateCode: 'AR' },
  { name: 'Fort Smith', stateCode: 'AR' },
  { name: 'Los Angeles', stateCode: 'CA' },
  { name: 'San Francisco', stateCode: 'CA' },
  { name: 'San Diego', stateCode: 'CA' },
  { name: 'Sacramento', stateCode: 'CA' },
  { name: 'San Jose', stateCode: 'CA' },
  { name: 'Denver', stateCode: 'CO' },
  { name: 'Colorado Springs', stateCode: 'CO' },
  { name: 'Hartford', stateCode: 'CT' },
  { name: 'New Haven', stateCode: 'CT' },
  { name: 'Wilmington', stateCode: 'DE' },
  { name: 'Dover', stateCode: 'DE' },
  { name: 'Miami', stateCode: 'FL' },
  { name: 'Orlando', stateCode: 'FL' },
  { name: 'Tampa', stateCode: 'FL' },
  { name: 'Jacksonville', stateCode: 'FL' },
  { name: 'Atlanta', stateCode: 'GA' },
  { name: 'Savannah', stateCode: 'GA' },
  { name: 'Honolulu', stateCode: 'HI' },
  { name: 'Hilo', stateCode: 'HI' },
  { name: 'Boise', stateCode: 'ID' },
  { name: 'Chicago', stateCode: 'IL' },
  { name: 'Springfield', stateCode: 'IL' },
  { name: 'Indianapolis', stateCode: 'IN' },
  { name: 'Fort Wayne', stateCode: 'IN' },
  { name: 'Des Moines', stateCode: 'IA' },
  { name: 'Cedar Rapids', stateCode: 'IA' },
  { name: 'Wichita', stateCode: 'KS' },
  { name: 'Kansas City', stateCode: 'KS' },
  { name: 'Louisville', stateCode: 'KY' },
  { name: 'Lexington', stateCode: 'KY' },
  { name: 'New Orleans', stateCode: 'LA' },
  { name: 'Baton Rouge', stateCode: 'LA' },
  { name: 'Portland', stateCode: 'ME' },
  { name: 'Augusta', stateCode: 'ME' },
  { name: 'Baltimore', stateCode: 'MD' },
  { name: 'Annapolis', stateCode: 'MD' },
  { name: 'Boston', stateCode: 'MA' },
  { name: 'Worcester', stateCode: 'MA' },
  { name: 'Detroit', stateCode: 'MI' },
  { name: 'Grand Rapids', stateCode: 'MI' },
  { name: 'Minneapolis', stateCode: 'MN' },
  { name: 'Saint Paul', stateCode: 'MN' },
  { name: 'Jackson', stateCode: 'MS' },
  { name: 'Gulfport', stateCode: 'MS' },
  { name: 'Kansas City', stateCode: 'MO' },
  { name: 'St. Louis', stateCode: 'MO' },
  { name: 'Helena', stateCode: 'MT' },
  { name: 'Billings', stateCode: 'MT' },
  { name: 'Omaha', stateCode: 'NE' },
  { name: 'Lincoln', stateCode: 'NE' },
  { name: 'Las Vegas', stateCode: 'NV' },
  { name: 'Reno', stateCode: 'NV' },
  { name: 'Manchester', stateCode: 'NH' },
  { name: 'Concord', stateCode: 'NH' },
  { name: 'Newark', stateCode: 'NJ' },
  { name: 'Jersey City', stateCode: 'NJ' },
  { name: 'Albuquerque', stateCode: 'NM' },
  { name: 'Santa Fe', stateCode: 'NM' },
  { name: 'New York City', stateCode: 'NY' },
  { name: 'Buffalo', stateCode: 'NY' },
  { name: 'Charlotte', stateCode: 'NC' },
  { name: 'Raleigh', stateCode: 'NC' },
  { name: 'Fargo', stateCode: 'ND' },
  { name: 'Bismarck', stateCode: 'ND' },
  { name: 'Columbus', stateCode: 'OH' },
  { name: 'Cleveland', stateCode: 'OH' },
  { name: 'Oklahoma City', stateCode: 'OK' },
  { name: 'Tulsa', stateCode: 'OK' },
  { name: 'Portland', stateCode: 'OR' },
  { name: 'Salem', stateCode: 'OR' },
  { name: 'Philadelphia', stateCode: 'PA' },
  { name: 'Pittsburgh', stateCode: 'PA' },
  { name: 'Providence', stateCode: 'RI' },
  { name: 'Newport', stateCode: 'RI' },
  { name: 'Columbia', stateCode: 'SC' },
  { name: 'Charleston', stateCode: 'SC' },
  { name: 'Sioux Falls', stateCode: 'SD' },
  { name: 'Rapid City', stateCode: 'SD' },
  { name: 'Nashville', stateCode: 'TN' },
  { name: 'Memphis', stateCode: 'TN' },
  { name: 'Houston', stateCode: 'TX' },
  { name: 'Dallas', stateCode: 'TX' },
  { name: 'Austin', stateCode: 'TX' },
  { name: 'San Antonio', stateCode: 'TX' },
  { name: 'Salt Lake City', stateCode: 'UT' },
  { name: 'Provo', stateCode: 'UT' },
  { name: 'Burlington', stateCode: 'VT' },
  { name: 'Montpelier', stateCode: 'VT' },
  { name: 'Richmond', stateCode: 'VA' },
  { name: 'Virginia Beach', stateCode: 'VA' },
  { name: 'Seattle', stateCode: 'WA' },
  { name: 'Spokane', stateCode: 'WA' },
  { name: 'Charleston', stateCode: 'WV' },
  { name: 'Huntington', stateCode: 'WV' },
  { name: 'Milwaukee', stateCode: 'WI' },
  { name: 'Madison', stateCode: 'WI' },
  { name: 'Cheyenne', stateCode: 'WY' },
  { name: 'Casper', stateCode: 'WY' },
] as const;
